name: TOC Interface Updater
description: Updates Interface versions found in World of Warcraft TOC metadata files
branding:
  icon: tag
  color: yellow
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/update.sh
      shell: bash
