name: TOC Interface Updater
description: Updates Interface versions found in World of Warcraft TOC metadata files
branding:
  icon: tag
  color: yellow
inputs:
  flavor:
    description: Interface version to default to
    default: retail
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/update.sh "${{ inputs.flavor }}"
      shell: bash
